version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 08:00
      timezone: America/Sao_Paulo
    commit-message:
      prefix: chore
    target-branch: canary
    reviewers:
      - pedrohenrique-ql
    groups:
      npm:
        patterns:
          - '*'

    ignore:
      - dependency-name: eslint
        update-types:
          - version-update:semver-major

      - dependency-name: glob
        update-types:
          - version-update:semver-major

      - dependency-name: '@types/glob'
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '08:00'
      timezone: America/Sao_Paulo
    commit-message:
      prefix: chore
    target-branch: canary
    reviewers:
      - pedrohenrique-ql
    groups:
      github-actions:
        patterns:
          - '*'
