name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  ci:
    name: CI

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Regex Match
        uses: ./.github/actions/regex-match-setup

      - name: Check formatting style
        uses: ./.github/actions/regex-match-style-check

      - name: Lint code and check types
        run: |
          pnpm concurrently --names lint,types \
            'pnpm lint .' \
            'pnpm types:check'

      - name: Prepare test environment
        run: pnpm run pre:test

      - name: Run unit tests
        run: pnpm test:vi run

      - name: Run integration tests
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            xvfb-run -a pnpm test:vsc
          else
            pnpm test:vsc
          fi
