name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Racha Aí
        uses: ./.github/actions/racha-ai-setup

      - name: Check formatting style
        uses: ./.github/actions/racha-ai-style-check

      - name: Lint code and check types
        run: |
          pnpm concurrently --names lint,types \
            'pnpm lint .' \
            'pnpm types:check'
