name: Publish to Visual Studio Marketplace

on:
  release:
    types:
      - published

concurrency:
  group: publish-vs-marketplace-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish:
    name: Visual Studio Marketplace Release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Publish
        run: npm run vscode:deploy
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
